title: 백가현, Gahyun Baek
description: Personal website for research
url: "https://gahyunBaek.github.io"
baseurl: ""

markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/
exclude:
  - ".jekyll-serve.log"

collections:
  paper_reviews:
    output: true
    permalink: /paper-reviews/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "paper_reviews"
    values:
      layout: review
  - scope:
      path: ""
    values:
      layout: default
